### PR TITLE
Add smithdc1 to recipe-maintainers

### PR DESCRIPTION
**Pull request by smithdc1**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding myself (a release manager of django-crispy-forms) to this maintainer list.

### CODE REVIEW

**Comment by smithdc1** [comment]
@conda-forge-admin, please rerender

**Comment by smithdc1** [comment]
@conda-forge/core This package is out of date and I'd like to see it updated as I'm one of the release managers for crispy-forms. 

I tried to ping the existing maintainers to release a new version (see #9 ) but they have not responded. Please can I ask you to review this request?

Thanks

David

**Comment by smithdc1** [comment]
@CJ-Wright apologies for the personal ping. I tried to ping the core team as per the docs but that doesn't seem to work for me.

I'm trying to get a new version of this package released and am trying to add myself to the maintainer list as the two folk currently on the list have not responded. I was wondering if you could help here?

Thanks 👍

**Comment by ocefpaf** [comment]
Please fix the linter and we'll merge this one.

Thanks for maintaining it!

**Comment by smithdc1** [comment]
@conda-forge-admin please ping team

**Pull request merged**
